### ISSUE TITLE
Show short commit hash on status when open diff

### ISSUE THREAD

**Issue by kmnk** [kmnk/gitn#14]
From [this comment](https://github.com/kmnk/gitn/pull/11#issuecomment-403669253) .

Now, We have no information to know commit hash on opened diff buffer.

I want to know it, when checking diff.

**Comment by kmnk** [comment]
Probably, use `:file` command

**Comment by kmnk** [comment]
https://github.com/kmnk/gitn/commit/5471ef21f7f95e74964ff374dc638ae38b28dc8d

Display it as buffer name by above merge commit.

**Comment by kmnk** [comment]
https://github.com/kmnk/gitn/pull/15#issuecomment-406794836

**Comment by kmnk** [comment]
@petobens Oh.. Sorry.. I'll fix it..

**Comment by kmnk** [comment]
Sorry, it was entry-level mistake.

Probably, fixed by https://github.com/kmnk/gitn/commit/71186197d11078cec8cac5b974f1eac763106a8e .

**Comment by petobens** [comment]
@kmnk thanks for looking into. The previous error is indeed fixed but now I'm seeing the following one:
```
[denite] Traceback (most recent call last):
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 132, in _start
[denite]     self.update_buffer()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 410, in update_buffer
[denite]     self.move_cursor()
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 547, in move_cursor
[denite]     self.do_action('preview')
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 710, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 315, in do_action
[denite]     return action['func'](context) if action['func'] else self._vim.call(
[denite]   File "/Users/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/kind/gitn_log.py", line 139, in action_preview
[denite]     self.vim.command('file gitn_diff_{0}'.format(t[0:7]))
[denite]   File "/usr/local/lib/python3.7/site-packages/neovim/api/nvim.py", line 272, in command
[denite]     return self.request('nvim_command', string, **kwargs)
[denite]   File "/usr/local/lib/python3.7/site-packages/neovim/api/nvim.py", line 170, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.7/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(file):E95: Buffer with this name already exists'
[denite] Please execute :messages command.
```

**Comment by kmnk** [comment]
@petobens oh.. I see.. duplicated buffer name..

My idea for resolving this issue is using buffer name to show short commit hash.
But it should not be used, apparently.

I'm reverting those commits, and think other idea to resolve it.

Thanks error reporting !

**Comment by kmnk** [comment]
Perhaps, using `:file!` command resolve that problem.
But problem that many buffer names is logged to buffer history is left.

hmmm..

**Comment by petobens** [comment]
Ok!

**Comment by petobens** [comment]
Hi @kmnk any updates on this? Do you plan to still work on gitn source? Thanks!

**Comment by kmnk** [comment]
Sorry for my no working for this project.

I work "with" `gitn` everyday. So I'll improve this plugin continually.

I can not make progress for a while.  
After resolve other tasks, I'll continue to make next commits.

Thanks

**Comment by petobens** [comment]
Awesome. Thanks
